name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Install Android SDK cmdline tools
        uses: android-actions/setup-android@v3

      - name: Install exact SDK versions
        run: |
          sdkmanager --install "platform-tools"
          sdkmanager --install "build-tools;34.0.0"
          sdkmanager --install "platforms;android-34"

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Fix gradlew permissions
        run: chmod +x gradlew

      - name: Clean build
        run: ./gradlew clean

      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: RootDetector-debug
          path: app/build/outputs/apk/debug/*.apk