name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - uses: android-actions/setup-android@v3

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Install required SDK versions
        run: |
          sdkmanager --install "platform-tools"
          sdkmanager --install "platforms;android-34"
          sdkmanager --install "build-tools;34.0.0"
          sdkmanager --install "cmdline-tools;latest"

      - name: Build
        run: gradlew assembleDebug --stacktrace --no-daemon

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk